# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/modelsim_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_16.2/projects/big_project/big_project.cache/wt [current_project]
set_property parent.project_path D:/vivado_16.2/projects/big_project/big_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog D:/vivado_16.2/projects/big_project/big_project.srcs/sources_1/new/header.vh
read_verilog -library xil_defaultlib {
  D:/vivado_16.2/projects/big_project/big_project.srcs/sources_1/new/ps2.v
  D:/vivado_16.2/projects/big_project/big_project.srcs/sources_1/new/uart_tx.v
  D:/vivado_16.2/projects/big_project/big_project.srcs/sources_1/new/uart_rx.v
  D:/vivado_16.2/projects/big_project/big_project.srcs/sources_1/new/mouse.v
  D:/vivado_16.2/projects/big_project/big_project.srcs/sources_1/new/bluetooth_clk.v
  D:/vivado_16.2/projects/big_project/big_project.srcs/sources_1/new/bluetooth.v
  D:/vivado_16.2/projects/big_project/big_project.srcs/sources_1/new/vga_display.v
  D:/vivado_16.2/projects/big_project/big_project.srcs/sources_1/new/vga_ctrl.v
  D:/vivado_16.2/projects/big_project/big_project.srcs/sources_1/new/main.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado_16.2/projects/big_project/big_project.srcs/constrs_1/new/1.xdc
set_property used_in_implementation false [get_files D:/vivado_16.2/projects/big_project/big_project.srcs/constrs_1/new/1.xdc]


synth_design -top main -part xc7a100tcsg324-1


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
